version: '3.2'
services:
  db:
    container_name: postgres
    image: postgres:10.6
    env_file:
      - .env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 300M
  web:
    container_name: blockscout
    env_file:
      - .env
    build:
      context: .
    volumes:
      - type: bind
        source: .
        target: /app
    deploy:
      resources:
        limits:
          cpus: '0.7'
          memory: 700M
    ports:
      - "4000:4000"
    depends_on:
      - db

    command:
      - ./run.sh