version: '3.2'
services:
  db:
    container_name: postgres
    image: postgres:10.6
    env_file:
      - .env
  web:
    container_name: blockscout
    env_file:
      - .env
    build:
      context: .
    volumes:
      - type: bind
        source: .
        target: /app
    ports:
      - "4000:4000"
    depends_on:
      - db

    command:
      - ./run.sh